#!/bin/sh
#
# The River configuration file.

# Set customizations.
riverctl attach-mode bottom
riverctl border-width 3

# Set colors.
riverctl background-color 0x303446
riverctl border-color-focused 0xBaBBF1
riverctl border-color-inactive 0x737994
riverctl border-color-urgent 0xE5C890

# Spawn programs.
riverctl map normal Super Return spawn foot
riverctl map normal Super G spawn "chromium --ozone-platform-hint=auto"

# Change layout.
riverctl map normal Super Space toggle-float
riverctl map normal Super H toggle-fullscreen

# Swap focus.
riverctl map normal Super K focus-view next
riverctl map normal Super L focus-view previous

# Swap views.
riverctl map normal Super+Shift K swap next
riverctl map normal Super+Shift L swap previous
riverctl map normal Super+Shift J send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift Semicolon send-layout-cmd rivertile "main-count -1"

# Resize views.
riverctl map normal Super A resize horizontal -100
riverctl map normal Super S resize vertical -100
riverctl map normal Super D resize vertical 100
riverctl map normal Super F resize horizontal 100

# Move views.
riverctl map normal Super+Shift A move left 100
riverctl map normal Super+Shift S move down 100
riverctl map normal Super+Shift D move up 100
riverctl map normal Super+Shift F move right 100

# Set tags.
for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super $i set-focused-tags $tags
  riverctl map normal Super+Shift $i set-view-tags $tags
done

# Set all tags.
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Close and exit.
riverctl map normal Super+Shift C close
riverctl map normal Super+Shift Q exit

# Set layout generator.
riverctl default-layout rivertile
rivertile -view-padding 10 -outer-padding 10 -main-ratio 0.5 &
