# $HOME/.config/X11/xinitrc

# !/bin/sh

function main() {
    mergeDefaultsAndKeymaps
    runInitrcScripts
    setBackgroundImage
    startWindowManager
}

function mergeDefaultsAndKeymaps() {
    userresources="${HOME}/.config/X11/Xresources"
    usermodmap="${HOME}/.config/X11/Xmodmap"
    sysresources="/etc/X11/xinit/.Xresources"
    sysmodmap="/etc/X11/xinit/.Xmodmap"

    if [ -f "${sysresources}" ]; then
        xrdb -merge "${sysresources}"
    fi
    if [ -f "${sysmodmap}" ]; then
        xmodmap "${sysmodmap}"
    fi
    if [ -f "${userresources}" ]; then
        xrdb -merge "${userresources}"
    fi
    if [ -f "${usermodmap}" ]; then
        xmodmap "${usermodmap}"
    fi
}

function runInitrcScripts() {
    if [ -d /etc/X11/xinit/xinitrc.d ]; then
        for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
            [ -x "${f}" ] && . "${f}"
        done
        unset f
    fi
}

function setBackgroundImage() {
    # Random background image
    background="$(find "$HOME/.local/share/backgrounds/" -maxdepth "1" -type "f" | shuf -n "1")"

    if [ -f "${background}" ]; then
        feh --bg-scale --no-fehbg "${background}"
    fi
}

function startWindowManager() {
    while true; do
        /usr/local/bin/dwm 2> /dev/null
    done
}

main
